
# Service ID
manual_level:
  # Service name as shown in UI
  name: Set Manual Level
  # Description of the service
  description: Sets manual level
   # Different fields that your service accepts
  fields:
    # Key of the field
    manual_level:
      # Field name as shown in UI
      name: Manual level
      # Description of the field
      description: Manual level setting
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: false
      # The default field value
      default: "Off"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "Off"
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"


sync_time:
  name: Synchronize time and date
  description: Synchronize time and date with device


timer_level:
  name: Set timer
  description: Set the ventilation timer
  fields:
    timer_level:
      name: Level
      description: Level setting
      required: true
      advanced: false
      default: "Level1"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
    time:
      name: Time
      description: Time of the timer (0 will disable the timer)
      required: true
      advanced: false
      default: 0
      number:
        min: 0
        max: 1440
        step: 10
        unit_of_measurement: "min"
        mode: slider

set_breeze:
  name: Set breeze
  description: Set the breeze function of the ventilation system
  fields:
    breeze_level:
      name: Level
      description: Ventilation level when breeze function is activated
      required: false
      advanced: false
      default: "Level3"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
    temperature:
      name: Temperature
      description: Temperature when the breeze function should be activated
      required: false
      advanced: false
      default: 18
      number:
        min: 15
        max: 35
        step: 10
        unit_of_measurement: "°C"
        mode: slider
    activate:
      name: Activate
      description: Activate or disable the breeze feature
      required: true
      advanced: false
      default: false
      bool:

set_day_night_time:
  name: Set day and night time
  description: Set the day and night time of the system
  fields:
    day:
      name: Start day
      description: Start time of the day
      required: true
      advanced: false
      default: false
      time:
    night:
      name: Start night
      description: Start time of the night
      required: true
      advanced: false
      default: false
      time:
    